version: '3'
services:
  config-server:
    image: obraganca/config-server:1.0
    container_name: config-server
    ports:
      - "8088:8088"
    
  
  eureka-server:
    image: obraganca/eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    image: obraganca/api-gateway:1.0
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  user-service:
    image: obraganca/user-service:1.0
    container_name: user-service
    ports:
      - "9002:9002"
    depends_on:
      - eureka-server
