version: '3'
services:
  config-server:
    image: obraganca/config-server:1.0
    networks:
      - collab-network
    container_name: config-server
    build: ./config-server
    restart: always
    ports:
      - "8088:8088"

  eureka-server:
    image: obraganca/eureka-server:1.0
    networks:
      - collab-network
    container_name: eureka-server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  api-gateway:
    image: obraganca/api-gateway:1.0
    networks:
      - collab-network
    container_name: api-gateway
    build: ./api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    links:
      - "eureka-server"
    depends_on:
      - eureka-server


  user-service:
    image: obraganca/user-service:1.0
    networks:
      - collab-network
    container_name: user-service
    build: ./user-service
    restart: always
    environment:
      - HOST_DB=jdbc:mysql://postgres-user-service:5432/user_service?useSSL=false
      - EUREKA_URL=http://eureka-server:8761/eureka
    ports:
      - "9002:9002"
    links:
      - "eureka-server"
    depends_on:
      - eureka-server
      - api-gateway

  email-service:
    image: obraganca/email-service:1.0
    networks:
      - collab-network
    container_name: email-service
    build: ./email-service
    restart: always
    environment:
      - HOST_DB=jdbc:mysql://postgres-user-service:5433/email_service?useSSL=false
      - EUREKA_URL=http://eureka-server:8761/eureka
    ports:
      - "9003:9003"
    links:
      - "eureka-server"
    depends_on:
      - eureka-server
      - api-gateway

networks:
  collab-network:
