spring:
  config:
    import: "optional:configserver:http://config-server:8088"
    activate:
      on-profile: docker


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

---
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:https://localhost:8088"
server:
  port: 8080

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
