server:
  port: 9002
spring:
  config:
    import: "optional:configserver:http://config-service:8088"
  jpa:
    defer-datasource-initialization: true
    properties.hibernate.format_sql: true
    generate-ddl: true
    hibernate.ddl.auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Specify PostgreSQL dialect

  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  application:
    name: user-service
  datasource:
    username: ${USER_DB:postgres}
    password: ${PASSWORD_DB:admin@123}
    url: ${HOST_DB:jdbc:postgresql://localhost:5432/user_service?useSSL=false}



eureka:
  instance:
    non-secure-port: 80
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}