server:
  port: 8088

spring:
  profiles:
    active: native
  application:
    name: config-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
