spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres-email-service:5432/email_service
    username: postgres
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

---
spring:
  application:
    name: email-service
  config:
    import: "optional:configserver:http://localhost:8088"

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/email_service
    username: postgres
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  jackson:
    serialization:
      order-map-entries-by-keys: false

server:
  port: 9003
security:
  basic:
    enabled: false

security.enable-csrf: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/